version: '3'
services:
  api:
    build: ./api
    volumes:
     - ./api/glm-1.Rds:/opt/api/glm-1.Rds
  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      - API_HOST=api
      - API_PORT=8000